Repository DguFarmSystem/HomePage-BE, pull requests merged in 2025-08, with the labels that each got.

#190 Refactor/#180 minigame review
  src/main/java/org/farmsystem/homepage/domain/minigame/dex/entity/PlantType.java
  src/main/java/org/farmsystem/homepage/domain/minigame/farm/entity/PlantStatus.java
  src/main/java/org/farmsystem/homepage/domain/minigame/farm/service/FarmService.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/controller/GardenController.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/AddTileDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/request/UpdateGardenObjectRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/request/UpdateGardenRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/response/GardenResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/response/PlacedObjectResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/response/UpdateGardenObjectResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/dto/response/UpdateGardenResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/entity/GardenTile.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/entity/PlacedObject.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/repository/GardenTileRepository.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/repository/PlacedObjectRepository.java
  src/main/java/org/farmsystem/homepage/domain/minigame/garden/service/GardenService.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/controller/InventoryController.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/dto/request/InventoryPlantUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/entity/Inventory.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/entity/PlantInventory.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/repository/InventoryRepository.java
  src/main/java/org/farmsystem/homepage/domain/minigame/inventory/service/InventoryService.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/controller/PlayerController.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/PlayerCurrencyDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/request/LevelUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/response/PlayerResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/entity/Player.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/service/DailyGameService.java
  src/main/java/org/farmsystem/homepage/domain/minigame/player/service/PlayerService.java
  src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/controller/SolarController.java
  src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/dto/SolarDTO.java
  src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/entity/SolarPowerStation.java
  src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/service/SolarService.java
Labels: ✨ feature

#198 [refactor] 블로그
  src/main/java/org/farmsystem/homepage/domain/blog/controller/AdminBlogController.java
  src/main/java/org/farmsystem/homepage/domain/blog/controller/BlogController.java
  src/main/java/org/farmsystem/homepage/domain/blog/controller/docs/AdminBlogApi.java
  src/main/java/org/farmsystem/homepage/domain/blog/controller/docs/BlogApi.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/request/BlogRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogApprovalResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/MyApplicationResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/PendingBlogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/service/AdminBlogService.java
  src/main/java/org/farmsystem/homepage/domain/blog/service/BlogService.java
Labels: ♻️ refactor

#206 [feat] #205 사용하지 않는 도커 이미지를 정리하도록 수정
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
Labels: ⚡ deploy
