Repository DguFarmSystem/HomePage-BE, pull requests merged in 2025-02, with the labels that each got.

#4 [docs] swagger 세팅
  build.gradle
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckController.java
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
Labels: 📝 docs

#10 [ chore ] CI/CD 설정 - application.yml 및 워크플로우
  .github/workflows/main.yml
  src/main/resources/application.yml
Labels: ⚡ deploy

#13 [feat] NEWS 기본 기능
  build.gradle
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
  src/main/java/org/farmsystem/homepage/domain/news/repository/NewsRepository.java
  src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
Labels: ✨ feature

#18 [refactor] news BaseTimeEntity, 에러코드, swagger-ui
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsApi.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/NewsApi.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
  src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ♻️ refactor

#21 [feat] User & Oauth 관련 API 구현
  build.gradle
  src/main/java/org/farmsystem/homepage/domain/apply/entity/PassedApply.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/PassedApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/OauthController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserInfoUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserTokenRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserVerifyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoUpdateResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserTokenResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserVerifyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/SocialType.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/Track.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/TrackHistory.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthTokenProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckController.java
  src/main/java/org/farmsystem/homepage/global/common/S3Service.java
  src/main/java/org/farmsystem/homepage/global/config/RedisConfig.java
  src/main/java/org/farmsystem/homepage/global/config/S3Config.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#23 [chore] - 서버분리 CI/CD 적용
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
Labels: ⚡ deploy

#24 [chore] #22 서버분리 CI/CD
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
Labels: ⚡ deploy

#27 [feat] #26 관리자 권한
  src/main/java/org/farmsystem/homepage/domain/user/entity/Role.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/TrackHistory.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/global/config/RedisConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/farmsystem/homepage/global/config/auth/jwt/JwtProvider.java
Labels: 🐛 bug, ✨ feature, ♻️ refactor

#38 [feat] FarmingLog 일반 유저용 기본 기능
  src/main/java/org/farmsystem/homepage/domain/farmingLog/controller/FarmingLogController.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/controller/FarmingLogLikeController.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/dto/FarmingLogRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/dto/FarmingLogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/Category.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLog.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLogLike.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogLikeRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#41 [feat] 지원 추가 구현
  src/main/java/org/farmsystem/homepage/domain/apply/controller/ApplyController.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/AnswerDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/ApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/CreateApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/LoadApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/CreateApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatusEnum.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/AnswerNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyAlreadySubmittedException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ChoiceNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/QuestionNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyStatusRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature, ♻️ refactor
