Repository DguFarmSystem/HomePage-BE, pull requests merged in 2025-05, with the labels that each got.

#149 [refactor] 랭킹 시스템 개선 & 출석체크 동시성 이슈 해결
  build.gradle
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/DailySeedRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/RankingCacheService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/RankingService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/SeedEventConsumer.java
  src/main/java/org/farmsystem/homepage/domain/user/service/SeedEventProducer.java
Labels: ♻️ refactor

#155 [deploy] update release/v1.1.3
  build.gradle
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/DailySeedRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/RankingCacheService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/RankingService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/SeedEventConsumer.java
  src/main/java/org/farmsystem/homepage/domain/user/service/SeedEventProducer.java
Labels: ⚡ deploy

#156 [fix] @Lock으로 인해 발생한 READ ONLY 트랜잭션 오류 해결
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
Labels: 🐛 bug

#157 [deploy] update release/v1.1.3
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
Labels: ⚡ deploy

#153 [feat] 태그 추가
  src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
  src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
Labels: ✨ feature

#159 [docs] 운영환경 임시토큰 발급 API Swagger 문서에서 제거
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
Labels: 📝 docs

#162 [feat] #160 Swagger에 Profile 설정 추가
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
Labels: ✨ feature

#163 [deploy] update release/v1.1.3
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
Labels: ⚡ deploy
