Repository DguFarmSystem/HomePage-BE, pull requests merged in 2025-04, with the labels that each got.

#132 [ feat ] 오늘의 씨앗 적립 현황 표시 & 토큰 재발급 API 수정
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/TodaySeedResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
Labels: 🐛 bug, ✨ feature

#133 [deploy] update v1.1.2
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/TodaySeedResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
Labels: ⚡ deploy

#136 [fix] #135 유저 새로 생성될 때 기존 랭킹 캐시 삭제
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
Labels: 🐛 bug

#134 [deploy] update v1.1.2 to main
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/TodaySeedResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
Labels: ⚡ deploy

#140 [refactor] Ranking API에 response 추가
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRankResponseDTO.java
Labels: ♻️ refactor

#141 [deploy] update v1.1.2
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRankResponseDTO.java
Labels: ⚡ deploy

#142 [deploy] update v1.1.2 to main
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRankResponseDTO.java
Labels: ⚡ deploy

#143 [bug] 알림 title 길이 제한, 파밍로그 알림 전송 조건
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLogLike.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogLikeRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
  src/main/java/org/farmsystem/homepage/domain/notification/entity/Notification.java
Labels: 🐛 bug

#144 [deploy] Update main v1.1.3
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLogLike.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogLikeRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
  src/main/java/org/farmsystem/homepage/domain/notification/entity/Notification.java
Labels: ⚡ deploy
