Repository DguFarmSystem/HomePage-BE, pull requests merged in 2025-03, with the labels that each got.

#44 [feat] 지원 priority 구현 및 버그 수정
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: 🐛 bug, ✨ feature

#50 [chore] #49 cors 프론트 배포 주소 추가
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
Labels: ⚡ deploy

#51 [chore] update develop
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ⚡ deploy

#48 [ docs ] 유저/인증 관련 API swagger 명세 작성 & redis 비밀번호 추가
  src/main/java/org/farmsystem/homepage/domain/apply/dto/AnswerDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: 🐛 bug, 📝 docs

#55 [chore] update develop
  src/main/java/org/farmsystem/homepage/domain/apply/dto/AnswerDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ⚡ deploy

#57 [fix] 스웨거 배포 주소 cors 에러 수정
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
Labels: 🐛 bug

#52 [ refactor ] 지원 N+1 문제 관련 코드 개선
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Answer.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
Labels: ♻️ refactor

#64 Release/v0.0.3
  src/main/java/org/farmsystem/homepage/domain/apply/controller/ApplyController.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/AnswerDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/ApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/CreateApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/LoadApplyRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/CreateApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Answer.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatusEnum.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/AnswerNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyAlreadySubmittedException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/ChoiceNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/exception/QuestionNotFoundException.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyStatusRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/controller/FarmingLogController.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/controller/FarmingLogLikeController.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/dto/FarmingLogRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/dto/FarmingLogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/Category.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLog.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLogLike.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogLikeRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogRepository.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
  src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
  src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ⚡ deploy

#66 [hotfix] Cors 설정에 www 추가
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
Labels: 🐛 bug, ⚙️ setting

#68 [fix] 지원서 학번 유니크 제약조건 삭제
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
Labels: 🐛 bug

#62 [docs] 이슈 템플릿 제목 수정
  .github/ISSUE_TEMPLATE/--bug----bug-report.md
  .github/ISSUE_TEMPLATE/--refactor-----refactoring-request.md
Labels: 📝 docs

#76 [fix] whitelist 수정
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
Labels: 🐛 bug

#77 Update release/v1.0.0
  src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
  src/main/java/org/farmsystem/homepage/domain/common/util/JamoUtil.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserSearchResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthTokenProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
Labels: ⚡ deploy

#80 [feat] 지원서 확인 API
  src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminApplyApi.java
  src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminApplyController.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/ApplyListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
Labels: ✨ feature

#87 [chore] cors 추가
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
Labels: ⚡ deploy

#88 [deploy] update release/v1.0.0
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
Labels: ⚡ deploy

#91 [feat] 사용자 관련 관리자 기능 구현
  src/main/java/org/farmsystem/homepage/domain/apply/entity/PassedApply.java
  src/main/java/org/farmsystem/homepage/domain/common/dto/response/PageResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AdminUserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AdminUserController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AuthController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/AdminUserRegisterRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/AdminUserSearchRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/AdminUserUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/PagingUserListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRegisterResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserSearchResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
  src/main/java/org/farmsystem/homepage/global/error/handler/GlobalExceptionHandler.java
Labels: ✨ feature

#98 [fix] validation 변경
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
Labels: 🐛 bug

#99 [deploy] update release/v1.0.0
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
Labels: ⚡ deploy

#100 [deploy] update main
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
Labels: ⚡ deploy

#90 [feat] news 이미지 추가
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsApi.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/NewsApi.java
  src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
  src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
Labels: ✨ feature

#45 [feat] 파밍로그 - 블로그 전체/유저/관리자 기능 구현
  src/main/java/org/farmsystem/homepage/domain/blog/controller/AdminBlogController.java
  src/main/java/org/farmsystem/homepage/domain/blog/controller/BlogController.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/request/BlogRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogApprovalResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/MyApplicationResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/dto/response/PendingBlogResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/blog/entity/ApprovalStatus.java
  src/main/java/org/farmsystem/homepage/domain/blog/entity/Blog.java
  src/main/java/org/farmsystem/homepage/domain/blog/entity/BlogCategory.java
  src/main/java/org/farmsystem/homepage/domain/blog/repository/BlogRepository.java
  src/main/java/org/farmsystem/homepage/domain/blog/service/AdminBlogService.java
  src/main/java/org/farmsystem/homepage/domain/blog/service/BlogService.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#102 [fix] #101 지원서 확인 API에 학번 추가
  src/main/java/org/farmsystem/homepage/domain/apply/dto/QuestionDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/ApplyListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
Labels: 🐛 bug

#104 [fix] #101 지원서 상세 확인 시 제출 트랙의 답변만 반환하도록 수정
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/SubmittedApplyResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
Labels: 🐛 bug

#105 [deploy] release/v1.0.1에 에러 수정
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
  src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
  src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
Labels: 🐛 bug, ⚡ deploy

#109 [chore] BE 레포 자동 리뷰어 지정
  .github/CODEOWNERS
Labels: ⚙️ setting

#110 [feat] 응원하기
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerApi.java
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerController.java
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/request/CheerRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/CheerResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/CheerUserDTO.java
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/PagingCheerListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/cheer/entity/Cheer.java
  src/main/java/org/farmsystem/homepage/domain/cheer/entity/CheerTag.java
  src/main/java/org/farmsystem/homepage/domain/cheer/repository/CheerRepository.java
  src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
Labels: ✨ feature

#115 [fix] 컴파일 에러 방지 위해 pageResponseDTO 위치 변경
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/PagingCheerListResponseDTO.java
Labels: 🐛 bug

#118 [fix] 페이징 관련 로직 개선 및 사용자 정보 관련 API 로직 수정/추가
  build.gradle
  src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminPassedApplyApi.java
  src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminPassedApplyController.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/request/PassedApplyRegisterRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/PassedApplyRegisterResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/entity/PassedApply.java
  src/main/java/org/farmsystem/homepage/domain/apply/repository/PassedApplyRepository.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/PassedApplyService.java
  src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/PagingCheerListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
  src/main/java/org/farmsystem/homepage/domain/common/dto/response/PageResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AdminUserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/AdminUserController.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
  src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/AdminUserUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserUpdateRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/OtherUserInfoResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/PagingUserListResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRegisterResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/TrackHistory.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/TrackHistoryRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
  src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
  src/main/java/org/farmsystem/homepage/global/error/exception/IllegalArgumentException.java
Labels: 🐛 bug

#116 [feat] 알림 기능
  src/main/java/org/farmsystem/homepage/domain/notification/controller/NotificationApi.java
  src/main/java/org/farmsystem/homepage/domain/notification/controller/NotificationController.java
  src/main/java/org/farmsystem/homepage/domain/notification/dto/NotificationResponseDto.java
  src/main/java/org/farmsystem/homepage/domain/notification/entity/Notification.java
  src/main/java/org/farmsystem/homepage/domain/notification/entity/NotificationType.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/NotificationEventListener.java
  src/main/java/org/farmsystem/homepage/domain/notification/repository/NotificationRepository.java
  src/main/java/org/farmsystem/homepage/domain/notification/service/NotificationService.java
  src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#117 [feat] 프로젝트
  src/main/java/org/farmsystem/homepage/domain/common/entity/Track.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/AdminProjectApi.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/AdminProjectController.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/HomeProjectApi.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/HomeProjectController.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/ProjectApi.java
  src/main/java/org/farmsystem/homepage/domain/project/controller/ProjectController.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/request/ProjectRequestDTO.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectApprovalResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectPageResultDTO.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectSimpleResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/project/entity/ApprovalStatus.java
  src/main/java/org/farmsystem/homepage/domain/project/entity/Project.java
  src/main/java/org/farmsystem/homepage/domain/project/repository/ProjectRepository.java
  src/main/java/org/farmsystem/homepage/domain/project/service/AdminProjectService.java
  src/main/java/org/farmsystem/homepage/domain/project/service/ProjectService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#113 [feat] csv파일로 합격자 정보 저장하기
  src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminPassedApplyApi.java
  src/main/java/org/farmsystem/homepage/domain/apply/dto/response/PassedApplyRegisterResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/apply/service/PassedApplyService.java
  src/main/java/org/farmsystem/homepage/domain/common/entity/Track.java
  src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectPageResultDTO.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#122 [feat] #121 cheered와 cheerer가 같을 경우 에러 발생
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerApi.java
  src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#129 [chore] #128 main 브랜치에 대한 블루/그린 반영
  .github/workflows/prod-cicd.yml
Labels: ⚡ deploy

#127 [feat] 알림 전송 코드 추가
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerController.java
  src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/notification/controller/NotificationApi.java
  src/main/java/org/farmsystem/homepage/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/CheerReceiveEvent.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/FarmingLogLikedEvent.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/NotificationEventListener.java
  src/main/java/org/farmsystem/homepage/domain/notification/service/NotificationService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ✨ feature

#130 [deploy] update v1.1.2 to main
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerApi.java
  src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerController.java
  src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
  src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
  src/main/java/org/farmsystem/homepage/domain/notification/controller/NotificationApi.java
  src/main/java/org/farmsystem/homepage/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/CheerReceiveEvent.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/FarmingLogLikedEvent.java
  src/main/java/org/farmsystem/homepage/domain/notification/event/NotificationEventListener.java
  src/main/java/org/farmsystem/homepage/domain/notification/service/NotificationService.java
  src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
Labels: ⚡ deploy
